version: '3.8'
services:
  autotest:
    build: ./autotest
    volumes:
      - ./autotest:/usr/src/autotest
    networks:
      - autotest-network

  jenkins:
    build: ./jenkins
    ports:
      - '8080:8080'
    volumes:
      - ./jenkins/jenkins-config:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - autotest-network

networks:
  autotest-network:
    driver: bridge
