version: "3.8"
services:
  jenkins:
    build: ./jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins/jenkins_configuration:/var/jenkins_home
      - ./jenkins/var/run/docker.sock:/var/run/docker.sock
      - ./autotest:/autotest
    networks:
      - autotest_network2

  autotest:
    build: ./autotest
    image: selenium/standalone-firefox:latest
    hostname: firefox
    privileged: true
    container_name: autotest
    shm_size: 2g
    ports:
      - "4442:4444"
      - "7901:7900"
    volumes:
      - ./autotest:/autotest
    # command: ["sh", "-c", ""]

    working_dir: /autotest
    networks:
      - autotest_network2

networks:
  autotest_network2:
    driver: bridge
