# FROM ianwalter/puppeteer:v4.0.0
# WORKDIR /app
# ADD . /app

# RUN npm install
# RUN npm run wdio

# # CMD ["npm", "run", "wdio"]

# # Используйте официальный образ Node.js как базовый
# FROM node:14

# # Установите рабочий каталог
# WORKDIR /autotest

# # Копируйте файлы проекта
# COPY . .

# # Установите зависимости проекта
# RUN npm install

# # Выставите порт, если это необходимо
# EXPOSE 3000

# # Запустите тесты
# CMD ["npm", "run", "wdio"]
