pipeline {
    agent any
    
    stages {
        stage('Install Docker CLI') {
            steps {
                sh 'curl -fsSL https://get.docker.com -o get-docker.sh'
                sh 'sh get-docker.sh'
                sh 'usermod -aG docker jenkins'
                sh 'docker restart jenkins'
            }
        }
        stage('Run Autotests') {
            steps {
                script {
                    docker.image('ianwalter/puppeteer:latest').inside {
                       sh './init.sh'
                    }
                }
            }
        }
    }
}