pipeline {
    agent any
    stages {
        stage('Run Tests in autotest Container') {
            steps {
                script {
                     sh 'docker run --rm autotest sh -c "./init.sh"'
                    // Запускаем команду в существующем контейнере autotest
                    // sh 'docker exec autotest sh -c "./init.sh"'
                }
            }
        }
    }
}
