pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
            }
        }
        stage('Checkout') {
            node {
              checkout scm 
    
        }
            // steps {
            //     checkout scm
            // }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm run wdio'
            }
        }
    }
}
